[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
components = { path = "./components" }
console_error_panic_hook = "0.1.7"
dto = { path = "../dto" }
gloo-net = "0.2.6"
futures = "0.3.28"
log = "0.4.18"
pages = { path = "./pages" }
router = { path = "./router" }
wasm-bindgen-futures = "0.4.36"
wasm-logger = "0.2.0"
yew = { version = "0.20.0", features = ["csr"] }
yew-router = "0.17.0"
yewdux = "0.9.3"
serde_json = "1.0.103"
stores = { path = "./stores" }
anyhow = "1.0.72"
web-sys = { version = "0.3.64", features = ["Window", "Location"] }
gloo-timers = { version = "0.2.6", features = ["futures"] }
