[workspace]
members = [
    "dto",
    "frontend",
    "frontend/components",
    "frontend/pages",
    "frontend/router",
    "frontend/stores",
    "server",
    "server/api",
    "server/service",
]
